

-- Table 'products'

DROP TABLE IF EXISTS products;

CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
);
COPY products(id)
FROM 'Users/rockw/hackreactor/SDC/csv/products.csv'
DELIMITER ','
CSV HEADER;

-- Table 'questions'

DROP TABLE IF EXISTS questions;

CREATE TABLE questions (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INTEGER NOT NULL,
  question_body VARCHAR (1000) NOT NULL,
  question_date TIMESTAMP NOT NULL,
  asker_name VARCHAR(60) NOT NULL,
  asker_email VARCHAR(60) NOT NULL,
  reported BOOLEAN,
  question_helpfulness INT NOT NULL,
  FOREIGN KEY (product_id)
    REFERENCES products (id),
      ON DELETE CASCADE
);
COPY questions(id, body, date_written, asker_email, reported, helpful, product_id)
FROM 'Users/rockw/hackreactor/SDC/csv/questions.csv'
DELIMITER ','
CSV HEADER;

-- Table 'answers'

DROP TABLE IF EXISTS answers;

CREATE TABLE answers (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id INTEGER NOT NULL,
  body VARCHAR (1000) NOT NULL,
  date_written TIMESTAMP NOT NULL,
  answerer_name VARCHAR (60) NOT NULL,
  answerer_email VARCHAR (60) NOT NULL,
  reported BOOLEAN,
  helpful INTEGER NOT NULL,
  -- photos SET NULL,
  FOREIGN KEY (question_id)
    REFERENCES questions (id),
      ON DELETE CASCADE
);
COPY answers(id, body, date_written, answerer_name, answerer_email, reported, helpful, question_id)
-- FROM '../CSV/answers.csv'
FROM 'Users/rockw/hackreactor/SDC/csv/answers.csv'
DELIMITER ','
CSV HEADER;


-- Table 'photos'

DROP TABLE IF EXISTS photos;

CREATE TABLE photos (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answer_id INTEGER NOT NULL,
  photo_url VARCHAR NOT NULL,
  FOREIGN KEY (answer_id)
      REFERENCES answers (id),
        ON DELETE CASCADE
);
COPY answers_photos(id, url, answer_id)
FROM 'Users/rockw/hackreactor/SDC/csv/answers_photos.csv'
DELIMITER ','
CSV HEADER;
